# 以我方蓝方为准
[robot]

[robot.0]
# 哨兵
positions = [
    [5.0, 7.5],     # 对方基地 1
    [6.5, 9.4],     # 对方基地 2
    [7.1, 6.7],     # 对方基地 3
    [18.0, 11.8],   # 我方前哨站
    [13.0, 3.6],    # 对方前哨站
    [16.0, 7.0],    # 资源岛盲区
]
[robot.1]
# 英雄
positions = [
    [10.4, 13.0],   # 前哨站射击点
    [7.6, 0.6],     # 对方飞坡前
    [3.5, 4.0],     # 符高入口
    [5.5, 1.2],     # 符高
    [1.8, 1.2],     # 补给区
    [16.0, 7.0],    # 资源岛盲区
    [27.0, 9.2],    # 我方基地盲区 1
    [27.0, 5.8],    # 我方基地盲区 2
]
[robot.2]
# 工程
positions = [
    [8.9, 10.9],    # 银矿
    [13.2, 6.7],    # 金矿
    [1.3, 3.2],     # 兑矿区
]
[robot.3]
# 步兵 3
positions = [
    [6.7, 10.0],    # 对方基地 1
    [7.5, 8.0],     # 对方基地 2
    [6.8, 6.3],     # 对方基地 3
    [1.8, 1.2],     # 补给区
    [16.0, 7.0],    # 资源岛盲区
    [20.5, 14.4],   # 我方飞坡盲区
    [7.6, 0.6],     # 对方飞坡前
    [3.5, 4.0],     # 符高入口
    [5.5, 1.2],     # 符高
]
[robot.4]
# 步兵 4
positions = [
    [6.7, 10.0],    # 对方基地 1
    [7.5, 8.0],     # 对方基地 2
    [6.8, 6.3],     # 对方基地 3
    [1.8, 1.2],     # 补给区
    [16.0, 7.0],    # 资源岛盲区
    [20.5, 14.4],   # 我方飞坡盲区
    [7.6, 0.6],     # 对方飞坡前
    [3.5, 4.0],     # 符高入口
    [5.5, 1.2],     # 符高
]
[robot.5]
# 步兵 5
positions = [
    [6.7, 10.0],    # 对方基地 1
    [7.5, 8.0],     # 对方基地 2
    [6.8, 6.3],     # 对方基地 3
    [1.8, 1.2],     # 补给区
    [16.0, 7.0],    # 资源岛盲区
    [20.5, 14.4],   # 我方飞坡盲区
    [7.6, 0.6],     # 对方飞坡前
    [3.5, 4.0],     # 符高入口
    [5.5, 1.2],     # 符高
]
